In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [9]:
df = pd.read_csv("/workspaces/Programming_for_datasci/L2/data/Sales_transactions_2.csv")

In [10]:
df.head()

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18045 entries, 0 to 18044
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction_ID        18045 non-null  str
 1   Order_ID              18045 non-null  str
 2   Customer_ID           18045 non-null  str
 3   Customer_Name         17937 non-null  str
 4   Customer_Age          17827 non-null  float64
 5   Customer_Gender       17883 non-null  str
 6   Customer_Segment      18045 non-null  str
 7   Order_Date            18045 non-null  str
 8   Order_Time            18045 non-null  str
 9   Sales_Channel         18045 non-null  str
 10  Store_ID              18045 non-null  str
 11  Store_Name            18045 non-null  str
 12  Country               18045 non-null  str
 13  Region                18045 non-null  str
 14  City                  18045 non-null  str
 15  Product_ID            18045 non-null  str
 16  Product_Name          17901 non-null  str
 17  Product_Category      18045 non-null  str
 18  Product_Subcategory   18045 non-null  str
 19  Quantity              18045 non-null  int64
 20  Unit_Price            18045 non-null  float64
 21  Discount_Percentage   18045 non-null  float64
 22  Sales_Amount          18045 non-null  float64
 23  Cost_Amount           18045 non-null  float64
 24  Profit                18045 non-null  float64
 25  Payment_Method        17898 non-null  str
 26  Order_Status          18045 non-null  str
 27  Shipping_Method       18045 non-null  str
 28  Delivery_Days         17883 non-null  float64
 29  Return_Flag           18045 non-null  str
 30  Return_Reason         1877 non-null   str
 31  Sales_Representative  18045 non-null  str
 32  Promotion_Code        8308 non-null   str
 33  Customer_Rating       14610 non-null  float64
 34  Inventory_Level       17847 non-null  float64
 35  Order_Year            18045 non-null  int64
dtypes: float64(9), int64(2), str(25)
memory usage: 5.0 MB

In [12]:
df.describe()

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17827.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,17883.000000,14610.000000,17847.000000,18045.000000
mean,38.916924,2.127127,232.685633,6.256858,457.309027,366.001156,91.404131,2.262204,3.985969,70.257914,2023.566417
std,10.727357,1.786212,294.208022,6.881178,856.597181,705.866738,167.827883,2.321656,1.008422,22.042609,1.118744
min,4.000000,-3.000000,21.390000,0.000000,16.680000,12.170000,-299.310000,0.000000,1.000000,0.000000,2022.000000
25%,32.000000,1.000000,53.380000,0.000000,78.530000,56.120000,19.480000,0.000000,4.000000,55.000000,2023.000000
50%,39.000000,2.000000,99.870000,5.000000,168.810000,122.300000,40.190000,1.000000,4.000000,70.000000,2024.000000
75%,46.000000,3.000000,285.580000,10.000000,472.450000,376.020000,93.270000,4.000000,5.000000,85.000000,2025.000000
max,112.000000,11.000000,1425.090000,110.000000,14303.070000,10791.000000,3512.080000,10.000000,5.000000,157.000000,2025.000000

In [13]:
df.isnull().sum()

Transaction_ID              0
Order_ID                    0
Customer_ID                 0
Customer_Name             108
Customer_Age              218
Customer_Gender           162
Customer_Segment            0
Order_Date                  0
Order_Time                  0
Sales_Channel               0
Store_ID                    0
Store_Name                  0
Country                     0
Region                      0
City                        0
Product_ID                  0
Product_Name              144
Product_Category            0
Product_Subcategory         0
Quantity                    0
Unit_Price                  0
Discount_Percentage         0
Sales_Amount                0
Cost_Amount                 0
Profit                      0
Payment_Method            147
Order_Status                0
Shipping_Method             0
Delivery_Days             162
Return_Flag                 0
Return_Reason           16168
Sales_Representative        0
Promotion_Code           9737
Customer_Rating          3435
Inventory_Level           198
Order_Year                  0
dtype: int64

In [14]:
df.shape

(18045, 36)

In [15]:
df.columns

Index(['Transaction_ID', 'Order_ID', 'Customer_ID', 'Customer_Name',
       'Customer_Age', 'Customer_Gender', 'Customer_Segment', 'Order_Date',
       'Order_Time', 'Sales_Channel', 'Store_ID', 'Store_Name', 'Country',
       'Region', 'City', 'Product_ID', 'Product_Name', 'Product_Category',
       'Product_Subcategory', 'Quantity', 'Unit_Price', 'Discount_Percentage',
       'Sales_Amount', 'Cost_Amount', 'Profit', 'Payment_Method',
       'Order_Status', 'Shipping_Method', 'Delivery_Days', 'Return_Flag',
       'Return_Reason', 'Sales_Representative', 'Promotion_Code',
       'Customer_Rating', 'Inventory_Level', 'Order_Year'],
      dtype='str')

In [17]:
df.dtypes

Transaction_ID              str
Order_ID                    str
Customer_ID                 str
Customer_Name               str
Customer_Age            float64
Customer_Gender             str
Customer_Segment            str
Order_Date                  str
Order_Time                  str
Sales_Channel               str
Store_ID                    str
Store_Name                  str
Country                     str
Region                      str
City                        str
Product_ID                  str
Product_Name                str
Product_Category            str
Product_Subcategory         str
Quantity                  int64
Unit_Price              float64
Discount_Percentage     float64
Sales_Amount            float64
Cost_Amount             float64
Profit                  float64
Payment_Method              str
Order_Status                str
Shipping_Method             str
Delivery_Days           float64
Return_Flag                 str
Return_Reason               str
Sales_Representative        str
Promotion_Code              str
Customer_Rating         float64
Inventory_Level         float64
Order_Year                int64
dtype: object

In [18]:
df.head(20)

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
5,T02003704,O0101852,C00959,Mia Miller,42.0,Non-binary,Corporate,2023-03-27,10:40:05,Retail Store,...,Completed,Pickup,0.0,No,NaN,Noah Wilson,SAVE10,1.0,35.0,2023
6,T02016542,O0116542,C02232,Evelyn Adams,46.0,Female,New Customer,2022-07-25,14:32:42,Online,...,Completed,Pickup,0.0,No,NaN,Ella Lewis,NaN,2.0,67.0,2022
7,T02013460,O0113460,C00719,Olivia Walker,44.0,Female,Consumer,2024-02-20,03:57:57,Online,...,Returned,Express,2.0,Yes,Damaged,Ella Lewis,NaN,5.0,59.0,2024
8,T02001029,O0101029,C01511,Emily Moore,54.0,Female,Consumer,2024-12-25,11:38:30,Online,...,Completed,Standard,7.0,No,NaN,Ella Lewis,NaN,NaN,57.0,2024
9,T02001635,O0101635,C04415,Freya Williams,49.0,Female,Consumer,2022-01-18,08:37:21,B2B Portal,...,Returned,Standard,7.0,Yes,Changed Mind,Olivia Martin,NaN,5.0,NaN,2022
10,T02017821,O0117821,C04919,Hannah King,42.0,Male,Consumer,2022-12-31,21:24:18,Online,...,Completed,Next Day,1.0,No,NaN,David Walker,BLACKFRIDAY25,4.0,48.0,2022
11,T02005146,O0105146,C01532,Lily Allen,22.0,Female,Consumer,2023-02-08,12:20:06,Retail Store,...,Completed,Standard,6.0,No,NaN,Mia Taylor,SAVE10,1.0,48.0,2023
12,T02004937,O0104937,C00848,Samuel Nelson,48.0,Male,Consumer,2022-12-05,22:08:10,Online,...,Completed,Express,2.0,No,NaN,Ella Lewis,NaN,5.0,109.0,2022
13,T02004775,O0104775,C03391,Oscar Adams,34.0,Female,Consumer,2024-09-03,16:57:56,Online,...,Completed,Express,1.0,No,NaN,James Anderson,NaN,5.0,68.0,2024
14,T02003373,O0103373,C01145,Ella Allen,32.0,Female,Returning Customer,2022-02-24,21:22:53,Online,...,Shipped,Standard,3.0,No,NaN,Amelia Jackson,NaN,2.0,91.0,2022
15,T02017546,O0117546,C00294,Alexander Smith,39.0,Male,Corporate,2025-05-03,11:11:09,Online,...,Completed,Standard,3.0,No,NaN,Liam Davis,NaN,5.0,84.0,2025
16,T02007214,O0107214,C01930,Amelia Johnson,50.0,Male,Consumer,2023-10-20,17:51:39,Retail Store,...,Shipped,Pickup,0.0,No,NaN,Henry White,NaN,5.0,65.0,2023
17,T02010877,O0105438,C03537,Nora King,37.0,Male,Small Business,2024-12-20,16:43:23,Online,...,Shipped,Pickup,0.0,No,NaN,Grace Harris,MOM15,5.0,48.0,2024
18,T02010845,O0110845,C03484,Grace Davis,42.0,Male,Consumer,2025-11-25,18:37:46,Online,...,Completed,Standard,6.0,No,NaN,Noah Wilson,NaN,5.0,81.0,2025
19,T02000770,O0100770,C00408,Theo Adams,27.0,Male,Consumer,2023-12-16,15:03:08,Retail Store,...,Processing,Pickup,0.0,No,NaN,Amelia Jackson,NaN,5.0,85.0,2023